server:
  port: 10004

rdb:
  mysql:
    url:  jdbc:mysql://localhost:3306/order
    driver: com.mysql.cj.jdbc.Driver
    username: test
    password: 123
    druid:
      maxWait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true

logging:
  level:
    root: INFO
    sample:
      mybatis:
        mapper: TRACE